//
// Created by Remus on 11/12/2022.
//

#ifndef INC_3DENGINE_REM_PIPELINECONFIGINFO_H
#define INC_3DENGINE_REM_PIPELINECONFIGINFO_H

#endif //INC_3DENGINE_REM_PIPELINECONFIGINFO_H

class RemPipelineConfigInfo
{

};